name: hsma5_pyshiny
channels:
  - conda-forge
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - numpy=1.24.3
  - pandas=2.0.2
  - pip:
    - shiny==0.3.3
    - shinywidgets==0.2.1
    - matplotlib==3.7.1
    - jupyter==1.0.0
    - ipykernel==6.23.1
    - ipyleaflet==0.17.3
